name: Build and Test

on:
  push:
jobs:
  build-and-test-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: '1.8'


    - name: Build with Maven
      run: mvn clean install
#      env:
#        MAVEN_OPTS: "-Dmaven.multiModuleProjectDirectory=$GITHUB_WORKSPACE -Djansi.passthrough=true -Dmaven.home=$MAVEN_HOME -Dclassworlds.conf=$MAVEN_HOME/bin/m2.conf -Dmaven.ext.class.path=$MAVEN_HOME/lib/maven-event-listener.jar -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8"

    - name: Run tests with Maven
      run: mvn test
#      env:
#        MAVEN_OPTS: "-Dmaven.multiModuleProjectDirectory=$GITHUB_WORKSPACE -Djansi.passthrough=true -Dmaven.home=$MAVEN_HOME -Dclassworlds.conf=$MAVEN_HOME/bin/m2.conf -Dmaven.ext.class.path=$MAVEN_HOME/lib/maven-event-listener.jar -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}