name: Build and Test

on:
  push:
jobs:
  build-and-test-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: 'Setup Java'
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'
        cache: 'maven'

    - name: Check Java and Maven versions
      run: |
        java -version
        mvn -version

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests with Maven
      run: mvn test

    - name: Run verify with Maven
      run: mvn verify

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}