#file: noinspection Annotator
name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Setup Java'
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'
          cache: 'maven'

      - name: 'Define Qodana Profile'
        run: |
          echo "version: \"1.0\"
          profile:
            name: qodana.recommended
          projectJDK: 21" > qodana.yaml

      - name: 'Run headless test'
        uses: coactions/setup-xvfb@v1
        with:
          run: mvn verify --file pom.xml

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1
        env:
           QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}