#file: noinspection Annotator
name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.14.0
        with:
          java-version: 8
          maven-version: 3.96

      - name: 'Define Qodana Profile'
        run: |
          echo "version: \"1.0\"
          profile:
            name: qodana.recommended
          projectJDK: 8" > qodana.yaml

      - name: 'Run Tests'
        run: mvn test

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        env:
           QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}